version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      - key=CnDwflTkzPzxviKR81DllzpoZBzCaDcsPrxclGkrg0Y=
    ports:
      - "8000:8000"
    # Other configuration options for your Python app container if needed
    tty: true

