name: Trigger auto deployment for otudy-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/otudy-api-AutoDeployTrigger-d179c6a0-acd9-4197-aaa0-9d5d72c15211.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OTUDYAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca7a387aa9f3acr.azurecr.io
          registryUsername: ${{ secrets.OTUDYAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OTUDYAPI_REGISTRY_PASSWORD }}
          containerAppName: otudy-api
          resourceGroup: otudy
          imageToBuild: ca7a387aa9f3acr.azurecr.io/otudy-api:${{ github.sha }}
          dockerfilePath: Dockerfile

     

